// <auto-generated />
using System;
using CMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CMS.Migrations.Customer
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20240130084627_Paymentmethodtablev4")]
    partial class Paymentmethodtablev4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CMS.Model.AddressTypes", b =>
                {
                    b.Property<int>("address_type_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("address_type_code"));

                    b.Property<string>("address_type_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("address_type_code");

                    b.ToTable("AddressTypes");
                });

            modelBuilder.Entity("CMS.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerPhone")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBecameCustomer")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtherPaymentDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethodCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerId");

                    b.HasIndex("PaymentMethodCode");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CMS.Model.PaymentMethod", b =>
                {
                    b.Property<string>("PaymentMethodCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PayMethodDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("PaymentMethodCode");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("CMS.Model.Customer", b =>
                {
                    b.HasOne("CMS.Model.PaymentMethod", "PaymentMethod")
                        .WithMany("Customers")
                        .HasForeignKey("PaymentMethodCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("CMS.Model.PaymentMethod", b =>
                {
                    b.Navigation("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
